### ISSUE TITLE
Continuous "fireCharacteristicUpdateCallback" errors on 5.2.0

### ISSUE THREAD

**Issue by a-dows** [plasticrake/homebridge-tplink-smarthome#144]
# Expected Behavior
No errors in regular use.

### Current Behavior
Homebridge log displays continuous errors on three devices (one HS110, and two plugs on a HS300).

### Steps to Reproduce (for bugs)
Start homebridge, view logs.
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/42701400/95932615-53622e00-0d9a-11eb-8493-f173fb2f8461.png">

### Versions

- **Node**:       12.18.1
- **Homebridge**: 1.2.3
- **OS**:       Homebridge Raspberry Pi Image

### Configuration

```json
    "name": "Kasa",
            "addCustomCharacteristics": false,
            "inUseThreshold": 60,
            "broadcast": "192.168.1.255",
            "pollingInterval": 10,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "timeout": 1000,
            "transport": "udp",
            "platform": "TplinkSmarthome"
```

### Homebridge Log / Command Output
[10/13/2020, 21:25:50] [Kasa] [Noise Machine] fireCharacteristicUpdateCallback [0.46719600000000006]: Unable to call updateCallback VoltAmperes
[10/13/2020, 21:25:50] [Kasa] [Noise Machine] fireCharacteristicUpdateCallback [116.799]: Unable to call updateCallback Volts
[10/13/2020, 21:25:50] [Kasa] [Noise Machine] fireCharacteristicUpdateCallback [0.023]: Unable to call updateCallback Watts
[10/13/2020, 21:25:50] [Kasa] [Plug 6] fireCharacteristicUpdateCallback [0.011]: Unable to call updateCallback Amperes
[10/13/2020, 21:25:50] [Kasa] [Plug 6] fireCharacteristicUpdateCallback [0.019]: Unable to call updateCallback KilowattHours

**Comment by antonme** [comment]
I see this behavior too.

Homebridge v1.2.3
Node.js v12.19.0

**Comment by plasticrake** [comment]
@antonme Do you also have `"addCustomCharacteristics": false,` in your config?

**Comment by plasticrake** [comment]
Should be fixed in v6.0.0

**Comment by antonme** [comment]
> @antonme Do you also have `"addCustomCharacteristics": false,` in your config?

Yes. 6.0.0 works fine for me, no more problems. Thank you!

**Comment by a-dows** [comment]
Verified fixed! Thank you for all your work on this @plasticrake! Plug-in is working beautifully now and I've got no more "no responses" anywhere in my house.

**Comment by raspberrycoulis** [comment]
@plasticrake - I'm on version 6.1.0 and I've suddenly started getting the same error messages above. I'm also on Homebridge version 1.3.1 if that helps. Have tried rolling back to version 6.0 of your plugin, but the issue still remains so have upgraded back to 6.1.0 again (still there).
